############################################################
# Dockerfile to build sandbox for executing user code
# Based on Ubuntu
############################################################

FROM sabbir1cse/ubuntu-python-pip-supervisor
MAINTAINER codecolon

# RUN apt-get update && \
#         apt-get install -y software-properties-common && \
#         apt-get install --reinstall ca-certificates && \
#         add-apt-repository ppa:deadsnakes/ppa && \
#         apt-get update -y  && \
#         apt-get install -y build-essential python3.6 python3.6-dev python3-pip && \
#         apt-get install -y git  && \
#         # update pip
#         python3.6 -m pip install pip --upgrade && \
#         python3.6 -m pip install wheel

# RUN apt-get update
# RUN apt-get install -y sudo

# RUN adduser --disabled-password --gecos '' docker
# RUN adduser docker sudo
# RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

# USER docker
# RUN sudo apt-get update
# RUN sudo apt-get -y install python
